spring:
  application:
    name: storefront_panoply
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
igdb:
  client-id: 1g2cdnqxkemqoru00cqqe0y4pnwhbk
  bearer-token: 250bhe0vyerqh0f3v3txd2knsgv7iz

# Feign timeouts and logging
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"